### PR TITLE
Add minimal bevy example

### PR DESCRIPTION
**Pull request by ostwilkens**
I was missing something like this personally. 
The existing example is great, but a bit complex for a first look.

### CODE REVIEW

**Comment by iMplode-nZ** [comment]
Perhaps this should be in bevy_building_blocks instead?

**Comment by bonsairobo** [comment]
Yea I like this idea. There are certainly a few more examples worth making:

- loading and meshing a VOX model
- ray-casting against voxels using OctreeSet
- infinite procedural terrain (2D and 3D noise)
- constructive solid geometry operations

@ostwilkens What would you like to see in a minimal bevy example?

**Comment by bonsairobo** [comment]
> Perhaps this should be in bevy_building_blocks instead?

Yea I've been thinking about this too. I want to at least finish up the LOD work before figuring out what to do with bevy-building-blocks.

**Comment by bonsairobo** [comment]
OH I was being sleepy and just realized this is a PR not an issue. Haha thanks!

**Review by bonsairobo — APPROVED** [review]

**Pull request merged**
